name: exam_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  get_it: ^8.2.0
  injectable: ^2.5.2
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  
dev_dependencies:
  build_runner: ^2.10.1

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.9.0

flutter:
  assets:
    - assets/fonts/roboto/
    - assets/fonts/inter/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-Bold.otf
        - asset: assets/fonts/inter/Inter-Medium.otf
  uses-material-design: true

flutter_assets:
  assets_path: assets/icons
  output_path: lib/core/const/
  filename: assets.dart