name: exam_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  fluttertoast: ^9.0.0
  get_it: ^8.2.0
  injectable: ^2.5.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  loader_overlay: ^5.0.0
  logger: ^2.6.0
  retrofit: ^4.6.0

flutter_native_splash:
  color: "#004182"
  android_12:
    icon_background_color: "#004182"

dev_dependencies:
  build_runner: ^2.10.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.9.0
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.1

flutter:
  generate: true
  assets:
    - assets/fonts/roboto/
    - assets/fonts/inter/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-Bold.otf
        - asset: assets/fonts/inter/Inter-Medium.otf
  uses-material-design: true
