name: exam_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  injectable: ^2.5.2

  dio: ^5.9.0
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  

dev_dependencies:
  injectable_generator: ^2.9.0
  build_runner: ^2.10.1

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
